{
 "title": "Air Quality",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"co2\")\n  |> filter(fn: (r) => r[\"iaq-board\"] == \"iaq-bedroom\" or r[\"iaq-board\"] == \"iaq-livingroom\" or r[\"iaq-board\"] == \"iaq-lab\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns:[\"host\", \"topic\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tvoc\")\n  |> filter(fn: (r) => r[\"iaq-board\"] == \"iaq-bedroom\" or r[\"iaq-board\"] == \"iaq-livingroom\" or r[\"iaq-board\"] == \"iaq-lab\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns:[\"host\", \"topic\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pm_10_concentration\"\n                       //or r[\"_measurement\"] == \"pm_2_5_concentration\" \n                       //or r[\"_measurement\"] == \"pm_1_concentration\" \n                       )\n  |> filter(fn: (r) => r[\"iaq-board\"] == \"iaq-bedroom\" or r[\"iaq-board\"] == \"iaq-livingroom\" or r[\"iaq-board\"] == \"iaq-lab\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns:[\"host\", \"topic\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"iaq-board\"] == \"iaq-bedroom\" or r[\"iaq-board\"] == \"iaq-livingroom\" or r[\"iaq-board\"] == \"iaq-lab\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns:[\"host\", \"topic\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PM Lab",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pm_10_concentration\"\n                       or r[\"_measurement\"] == \"pm_2_5_concentration\" \n                       or r[\"_measurement\"] == \"pm_1_concentration\" \n                       )\n  |> filter(fn: (r) => r[\"iaq-board\"] == \"iaq-lab\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns:[\"host\", \"topic\"])\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}