{
 "title": "Hardware",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "machines",
    "label": "Machines",
    "query": "bragi,charon,sentinel,citadel,forge,lab,tars,workstation,alesia,eva,etna,thule,palantir"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Available %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\", \"cpu\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu_temp\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Available %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"available_percent\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Available (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"available\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1024.0/1024.0/1024.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Available % on /",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"path\"] == \"/\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\", \"path\", \"mode\", \"fstype\", \"device\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Swap Available (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_free\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1024.0/1024.0/1024.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Write (MB/s) Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> derivative(unit: 1s, nonNegative: false)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value / 1024.0/1024.0 }))\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Disk Read (MB/s) Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> derivative(unit: 1s, nonNegative: false)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value / 1024.0 / 1024.0 }))\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_users\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_unique_users\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"hardware\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"iops_in_progress\")\n  |> filter(fn: (r) => contains(value: r.host, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _field: r.host }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}