{
 "title": "Suricata Log Eve JSON",
 "description": "Example using Suricata HoneyPot T-Pot TCE\r\nEve.json",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Suricata Signature",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (alert_signature)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__=\"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata IP's",
   "type": "piechart",
   "description": "Change Max Data points in Loki query to obtain more records",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (src_ip)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Type Rules",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (event_type)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Proto",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (proto)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Destination Ports",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (dest_port)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Severity",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (alert_severity)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Category",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (alert_category)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Signature ID",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (alert_signature_id)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata IP's time series",
   "type": "timeseries",
   "description": "Change Max Data points in Loki query to obtain more records",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 43 },
   "targets": [
    {
     "expr": "topk(10, sum by (src_ip)\r\n(count_over_time({source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | __error__ = \"\" \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata raw log eve.json",
   "type": "logs",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{source=\"eve_json\"} | json | line_format \"{{.message}}\" | json | json\r\n| line_format \" Client {{.src_ip_extracted}} with proto {{.proto_extracted}} event {{.event_type}} hits signature {{.alert_signature}} category {{.alert_category}} and Signature ID {{.alert_signature_id}}\""
    }
   ]
  }
 ]
}