-- NOTE: to iterate quickly remove symlink generated by home-manager and link this file
local ok, git = pcall(require, "git")
if ok and git and type(git.setup) == "function" then
  git:setup { order = 0 }
end


-- Show user/group of files in status bar
Status:children_add(function()
	local h = cx.active.current.hovered
	if not h or ya.target_family() ~= "unix" then
		return ""
	end

	return ui.Line {
		ui.Span(ya.user_name(h.cha.uid) or tostring(h.cha.uid)):fg("magenta"),
		":",
		ui.Span(ya.group_name(h.cha.gid) or tostring(h.cha.gid)):fg("magenta"),
		" ",
	}
end, 500, Status.RIGHT)

-- Show username and hostname in header
Header:children_add(function()
	if ya.target_family() ~= "unix" then
		return ""
	end
	return ui.Span(ya.user_name() .. "@" .. ya.host_name() .. ":"):fg("blue")
end, 500, Header.LEFT)

local ok, allmytoes = pcall(require, "allmytoes")
if ok and allmytoes and type(allmytoes.setup) == "function" then
    allmytoes:setup {
        sizes = {"n", "l", "x", "xx"},
    }
end

-- custom line_mode
function Linemode:file_meta()
	local time = math.floor(self._file.cha.mtime or 0)
	if time == 0 then
		time = ""
	elseif os.date("%Y", time) == os.date("%Y") then
		time = os.date("%b %d %H:%M", time)
	else
		time = os.date("%b %d  %Y", time)
	end

	local size = self._file:size()
    local perm = self._file.cha:perm()

	local user = ya.user_name and ya.user_name(self._file.cha.uid) or self._file.cha.uid
	local group = ya.group_name and ya.group_name(self._file.cha.gid) or self._file.cha.gid
	return string.format("%s:%s %s %s %s", user, group, perm, size and ya.readable_size(size) or "-", time)
end
