[mgr]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true
linemode = "permissions"
show_symlink = true

[open]
rules = [
  { mime = "text/*", use = "edit" },

  { name = "*.v", use = "edit" },
  { name = "*.json", use = "edit" },
  { name = "*.html", use = [
    "open",
    "edit",
  ] },
]

[opener]
edit = [
  { run = 'nixvim "$@"', block = true, for = "unix" },
  { run = 'nixvim-light "$@"', block = true, for = "unix" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

# use nixvim-light for bulk rename
[[opener.bulk-rename]]
run = 'nixvim-light "$@"'
block = true

[[open.prepend_rules]]
name = "bulk-rename.txt"
use = "bulk-rename"

# archive view
[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run = "lsar"

[[plugin.prepend_previewers]]
mime = "application/octet-stream" # zip ??
run = "lsar"

[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run = "lsar"

[input]
find_origin = "bottom-left"
shell_origin = "bottom-left"
search_origin = "bottom-left"
filter_origin = "bottom-left"
