[mgr]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true
linemode = "permissions"
show_symlink = true

[open]
rules = [
  { mime = "text/*", use = "edit" },

  { name = "*.v", use = "edit" },
  { name = "*.json", use = "edit" },
  { name = "*.html", use = [
    "open",
    "edit",
  ] },
]

[opener]
edit = [
  { run = 'nixvim "$@"', block = true, for = "unix" },
  { run = 'nixvim-light "$@"', block = true, for = "unix" },
]

# use nixvim-light for bulk rename
[[opener.bulk-rename]]
run = 'nixvim-light "$@"'
block = true

[[open.prepend_rules]]
name = "bulk-rename.txt"
use = "bulk-rename"


[plugin]
prepend_previewers = [
  { name = "*.stl", run = "allmytoes" },
  # Show archive contents
  { mime = "application/{,g}zip", run = "lsar" },
  { mime = "application/octet-stream", run = "lsar" },                       # zip ??
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", run = "lsar" },
  # Allmytoes doesn't handle these by default
  { mime = "image/svg+xml", run = "magick" },
  { mime = "image/heic", run = "magick" },
  { mime = "image/jxl", run = "magick" },
  # Handle other image types with allmytoes
  { mime = "image/*", run = "allmytoes" },
  # NOTE: you might need to remove /tmp/yazi- folders if some previews were already generated (maybe incorrectly or blank)
]

prepend_preloaders = [
  { name = "*.stl", run = "allmytoes" },
  # Allmytoes doesn't handle these by default
  { mime = "image/svg+xml", run = "magick" },
  { mime = "image/heic", run = "magick" },
  { mime = "image/jxl", run = "magick" },
  # Handle other image types with allmytoes
  { mime = "image/*", run = "allmytoes" },
]

prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]

[input]
find_origin = "bottom-left"
shell_origin = "bottom-left"
search_origin = "bottom-left"
filter_origin = "bottom-left"
